export const ACRONYMS = {
  'AMP': 'Asset Management Period — the 5-year regulatory cycle during which Ofwat sets price controls',
  'RCV': 'Regulatory Capital Value — the regulatory asset base on which SVT earns its allowed return',
  'CMA': 'Competition and Markets Authority — the independent body that hears appeals against Ofwat price determinations',
  'WACC': 'Weighted Average Cost of Capital — the blended cost of equity and debt used to set SVT\'s allowed return',
  'RoRE': 'Return on Regulatory Equity — measures performance incentive payments as a percentage of regulatory equity',
  'WINEP': 'Water Industry National Environment Programme — statutory environmental improvement obligations set by regulators',
  'P10': '10th percentile outcome — represents a bad year for performance where ODI penalties are likely',
  'P90': '90th percentile outcome — represents a good year for performance where ODI rewards are likely',
  'PR24': '2024 Price Review — Ofwat\'s determination of price controls for 2025-2030',
  'ODI': 'Outcome Delivery Incentive — financial reward or penalty linked to SVT\'s performance against targets',
  'PCL': 'Performance Commitment Level — the target SVT must meet to avoid ODI penalties',
  'AICR': 'Adjusted Interest Cover Ratio — measures SVT\'s ability to service its debt from operating cash flow',
  'FFO': 'Funds From Operations — operating cash flow before working capital changes',
  'CPIH': 'Consumer Prices Index including Housing costs — the inflation measure used to index RCV from AMP7 onwards',
  'PAYG': 'Pay As You Go — the portion of totex recovered through bills in the current period rather than added to RCV',
  'totex': 'Total Expenditure — the combined capital and operating expenditure allowed by Ofwat',
  'WaSC': 'Water and Sewerage Company — a company licensed to provide both water and sewerage services',
  'WoC': 'Water Only Company — a company licensed to provide water services only',
  'SVE': 'Severn Trent (appointed company code) — the regulated entity within the Severn Trent group',
  'SVT': 'Severn Trent Water — the operating water and sewerage company serving the Midlands',
  'DPC': 'Direct Procurement for Customers — Ofwat\'s mechanism for large infrastructure projects',
  'PCC': 'Per Capita Consumption — average daily water use per person in litres',
  'CRI': 'Compliance Risk Index — a measure of drinking water quality compliance',
}
